baseURL = 'https://blog.yunzheng.space/'
locale = 'zh-CN'
defaultContentLanguage = 'zh'
title = '芸峥博客'
theme = 'yunzheng'
[pagination]
  pagerSize = 10
enableRobotsTXT = true

[params]
  author = '芸峥 (Zhenyun Sun)'
  description = '芸峥的个人博客 — 网络、技术、生活'
  mainSite = 'https://yunzheng.space'

[markup]
  [markup.highlight]
    style = 'monokailight'
    lineNos = false
    noClasses = true
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
  home = ['HTML', 'RSS']

[menu]
  [[menu.main]]
    name = '首页'
    url = '/'
    weight = 1
  [[menu.main]]
    name = '归档'
    url = '/archives/'
    weight = 2
  [[menu.main]]
    name = '关于'
    url = 'https://yunzheng.space/index.zh.html'
    weight = 3
